### ISSUE TITLE
inefficiency caused by double event creation and extra field lookup

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-codec-json_lines#17]
the current codec implementation leverages the **lines** codec for doing the line parsing. The problem is that [the line codec `decode` method is called](https://github.com/logstash-plugins/logstash-codec-json_lines/blob/1eb838d12321a05f291c3836dce51c230605f915/lib/logstash/codecs/json_lines.rb#L40) which produces and event and then [a new event is created using the json deserialization of the previous event message field](https://github.com/logstash-plugins/logstash-codec-json_lines/blob/1eb838d12321a05f291c3836dce51c230605f915/lib/logstash/codecs/json_lines.rb#L55).

This means that for each input line, and extra and superfluous event is created and an extra event field lookup is done.

Since the line parsing logic is so simple, we just should directly use the buffered tokenizer here and not rely on the line codec.

**Comment by jordansissel** [comment]
+1 your proposal.

**Comment by guyboertje** [comment]
Are we handling remainder flushing on close at all - in the current impl?

**Comment by jsvd** [comment]
I made some arguments against this through another channel on the overall choice of buftok vs line codec:

```
implementation-wise I dont know if using the line codec makes the code more complex, which is my only concern on my suggestion.

That aside I see multiple benefits:
* reusing code
* one less place we have to maintain the contract of an external dependency
* using the codec this way helps us reinforce what one day might become the line tokenizer
```

Also, the performance gain is unknown and, for me, doesn't justify hardwiring buftok in json_lines (and multiline).

That said, for coherence sake and dismissing the performance argument, I'm +1 on going with this proposal if https://github.com/logstash-plugins/logstash-codec-multiline/issues/26 is accepted

**Comment by colinsurprenant** [comment]
given the simplicity of this implementation (without the boilerplate, literally 1 line `@buffer.extract(data).each do |line|` ) I think DRYness is not really a concern and I'd rather opt for performance.

**Comment by guyboertje** [comment]
+1 to use buftok and to fix the "flush if remainder" problem.

**Comment by guyboertje** [comment]
+1 to improve performance too.

**Comment by guyboertje** [comment]
Here too is a flavour mismatch if json_lines is used with the file input, and because there is no flush one gets absolutely no events generated at all, not even incorrect ones.

**Comment by colinsurprenant** [comment]
@guyboertje codec `flush` is meant as a final flush, why events are not generated when used with file input?

**Comment by suyograo** [comment]
Fixed in #18

**Comment by guyboertje** [comment]
@colinsurprenant 

> codec flush is meant as a final flush, why events are not generated when used with file input?

Because json_lines does not implement a flush method!

**Comment by colinsurprenant** [comment]
@guyboertje but you said «if json_lines is used with the file input, and because there is no flush one gets **absolutely no events generated at all**»

So are «absolutely no events generated at all» or is there potentially a missing last event because there is no final flush? 

It is important that this be clarified because if no events at all are generated by a lacking flush when used with the new file input, we do have a serious problem and need to update all/most codecs?

**Comment by colinsurprenant** [comment]
after discussions, we agree a flush method is required for the shutdown case where an incomplete line was buffered. It is pretty obvious this incomplete line will end up generating a json parser error but at least there will be a log trace for it.

**Comment by colinsurprenant** [comment]
followup issue in #20
