### ISSUE TITLE
json_lines codec does not work for file input containing json lines

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-codec-json_lines#7]
There is some conflicting information on whether json_lines can be used with file input.  The documentation (https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json_lines.html) indicates that for line-oriented json in file inputs to use the json codec instead.

But then this Logstash ticket (https://logstash.jira.com/browse/LOGSTASH-1644) suggests that it should work.  Here is an example of using the file input with json_lines on LS 1.5 where it does not produce any events:

```
input { 
file { 
codec => "json_lines" 
path => "path/simple.json" 
discover_interval => 10 
sincedb_path => "/dev/null" 
start_position => "beginning" 
} 
}

output { 
stdout { 
codec => "json" 
} 
}
```

simple.json contains:
```
{"field": "value1"}
{"field": "value2"}
```

The above does not return anything.  But as soon as the codec is changed from `json_lines` to `json`, it  immediately starts working.  Looked at this briefly, it appears that `FileWatch::BufferedTokenizer.extract` is not returning any lines when json_lines is used.

**Comment by diegodurs** [comment]
:+1: the documentation is confusing!

**Comment by guyboertje** [comment]
Yes the doc at https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json_lines.html is a bit unclear.  I have improved it. PR pending.

However, the truth is, by design, the file input and json_lines codec do not interoperate.

Docs Preview:
```
This codec will decode streamed JSON that is newline delimited.
Encoding will emit a single JSON string ending in a `\n`
NOTE: Do not use this codec if your source input is line-oriented JSON, for
example, redis or file inputs. Rather, use the json codec.
More info: This codec is expecting to receive a stream (string) of newline
terminated lines. The file input will produce a line string without a newline.
Therefore this codec cannot work with line oriented inputs.
```

**Comment by guyboertje** [comment]
PR #10 closes this issue.
